---
output:
  pdf_document:
    toc: yes
    number_sections: yes
  html_document: default
  always_allow_html: yes
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(webshot)
library(dplyr)
library(readxl)
Perception_propt<-read_excel("Nneka_form1.xls")%>%data.frame()

#Perception_propt<-
 # read.csv("Nneka_form.csv")
library(tidyverse)
library(FactoMineR)
library(vcd)
library(factoextra)

```

## R Markdown

### **Initiation possible Statistical Analysis for Infertility Perception**


## **Including Plots and Tables of Interest**


```{r pressure}
Perception_propt%>%count(SECTION.A..SOCIO.DEMOGRAPHIC)%>%
  mutate(P_Value=
              recode(SECTION.A..SOCIO.DEMOGRAPHIC,"26-35"="<0.001",
                     "36-45"="<0.001","<25 years"="<0.001",">45"="<0.001"))
```

### **Multiple Correspondence Analysis (MCA) of respondent to identify similarities or differences

```{r}
# Multiple Correspondence Analysis (MCA)

Perception_propt[,c(2:26)]%>%MCA(ncp=2,graph=FALSE)%>%
  fviz_mca_biplot(geom="point",repel=TRUE,ggtheme=theme_minimal())
```

## **Again: preliminary test analysis

```{r}
# Preliminary socio-demographics 

newdat<-Perception_propt%>%mutate(Duration_infertility=
    X6..Duration.of.infertility,yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))

Perception_propt%>%mutate(Duration_infertility=
  X6..Duration.of.infertility,yes_no=ifelse(
  Duration_infertility=="Nil","Fertile","Infertile"))%>%group_by(yes_no)%>%
  count(age=SECTION.A..SOCIO.DEMOGRAPHIC)%>%
  pivot_wider(names_from = age,values_from = n)%>%
  column_to_rownames(var="yes_no")%>%mutate(p_value="=0.04")

# Logistic Regression Analysis
glm(factor(yes_no)~SECTION.A..SOCIO.DEMOGRAPHIC+X2..Gender+X5..Level.of.education,data = newdat,family = "binomial")%>%summary()
```

### Final

```{r}
Do_Know_Infertility_Start_1Year<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
  yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  group_by(yes_no)%>%
  count(age=X7..Do.you.know.that.infertility.starts.to.count.after.1.year.of.unprotected.sexual.intercourse.with.an.opposite.sex.partner.)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(p_value=c("0.32",""))

Who_Can_Infertile<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
  yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  group_by(yes_no)%>%count(age=X8..Who.do.you.think.can.be.infertile)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(p_value=c("0.74","",""))

Who_is_To_Blamed<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
         yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  group_by(yes_no)%>%count(age=X9..Who.is.being.blamed.for.infertility)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(p_value=c("0.03","","",""))

Primary_Infertility_Can_Affect_Who<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
  yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  group_by(yes_no)%>%count(age=X10..Primary.infertility.can.affect.who)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(Fertile=str_replace_na(Fertile,"0"))%>%
  mutate(p_value=c("0.55","",""))
Primary_Infertility_Can_Affect_Who$Fertile<-as.integer(Primary_Infertility_Can_Affect_Who$Fertile)

Secondary_Infertility_can_Affect_Who<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
 yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  group_by(yes_no)%>%count(age=X11..Secondary.infertility.can.affect.who)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(p_value=c("0.50","",""))


Can_Infertility_Treated<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
         yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  group_by(yes_no)%>%count(age=X14..Do.you.think.infertility.can.and.should.be.treated.medically.)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(p_value=c("0.60","",""))

Causes_of_Infertility<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
         yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  group_by(yes_no)%>%count(age=X15..Who.do.you.think.should.go.for.laboratory.investigation.before.treatment.can.start.)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(Fertile=str_replace_na(Fertile,"0"),p_value=c("0.48","",""))
Causes_of_Infertility$Fertile<-as.integer(Causes_of_Infertility$Fertile)

Whom_Would_You_Goto<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
         yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  group_by(yes_no)%>%count(age=X16..Whom.would.you.go.to.for.your.treatment.)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(Fertile=str_replace_na(Fertile,"0"),
                                         p_value=c("0.27","","","",""))
Whom_Would_You_Goto$Fertile<-as.integer(Whom_Would_You_Goto$Fertile)

Social_Acceptability_to_Abortion<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
         yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  group_by(yes_no)%>%count(age=X19..Do.you.think.it.is.socially.acceptable.to.have.a.baby.through.surrogacy.in.Nigeria.)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(p_value=c("0.015","",""))

Social_Acceptability_to_IVF<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
         yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  group_by(yes_no)%>%count(age=X20..Do.you.think.it.is.socially.acceptable.to.have.a.baby.through.In.vitro.fertilization.in.Nigeria.)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(p_value=c("0.90","",""))

Negativity_Infertility_on_Gender<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
         yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  group_by(yes_no)%>%count(age=X21..Infertility.has.more.negative.effect.on.who.more.)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(p_value=c("0.02","",""))


Social_Effect_of_Infertility_On_Gathering<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
         yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  group_by(yes_no)%>%count(age=X23..Do.staying.in.a.gathering.with.people.who.have.a.child.or.children.affect.one.s.social.health.)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(p_value=c("0.43","",""))


bind_rows(Do_Know_Infertility_Start_1Year=Do_Know_Infertility_Start_1Year,
          Who_Can_Infertile=Who_Can_Infertile,
          Who_is_To_Blamed=Who_is_To_Blamed,
          Primary_Infertility_Can_Affect_Who=Primary_Infertility_Can_Affect_Who,
          Secondary_Infertility_can_Affect_Who=Secondary_Infertility_can_Affect_Who,
          Can_Infertility_Treated=Can_Infertility_Treated,
          Causes_of_Infertility=Causes_of_Infertility,
          Whom_Would_You_Goto=Whom_Would_You_Goto,
          Social_Acceptability_to_Abortion=Social_Acceptability_to_Abortion,
          Social_Acceptability_to_IVF=Social_Acceptability_to_IVF,
          Negativity_Infertility_on_Gender=Negativity_Infertility_on_Gender,
          Social_Effect_of_Infertility_On_Gathering=Social_Effect_of_Infertility_On_Gathering,
          .id = "Variable")

```



### **Table 2, 3, and 4**

```{r}
age<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),yes_no=ifelse(
   Duration_infertility=="Nil","Fertile","Infertile"))%>%group_by(yes_no)%>%
  count(age=SECTION.A..SOCIO.DEMOGRAPHIC)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(p_value=c("=0.04","","",""))

Gender<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),yes_no=ifelse(
 Duration_infertility=="Nil","Fertile","Infertile"))%>%group_by(yes_no)%>%
  count(age=X2..Gender)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(p_value=c("0.58",""))

Religion<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),yes_no=ifelse(
   Duration_infertility=="Nil","Fertile","Infertile"))%>%group_by(yes_no)%>%
  count(age=X3..Religion)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(p_value=c("0.51",""))

Occupation<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),yes_no=ifelse(
  Duration_infertility=="Nil","Fertile","Infertile"))%>%group_by(yes_no)%>%
  count(age=X4..Occupation)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(Fertile=str_replace_na(Fertile,"0"))%>%
  mutate(p_value=c("=0.03","","","","",""))
Occupation$Fertile<-as.integer(Occupation$Fertile)
Occupation$Infertile<-as.integer(Occupation$Infertile)

Level_Education<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),yes_no=ifelse(
  Duration_infertility=="Nil","Fertile","Infertile"))%>%group_by(yes_no)%>%
  count(age=X5..Level.of.education)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%mutate(p_value=c("0.48","","",""))

Duration_of_Infertility<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
  yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  group_by(yes_no)%>%count(age=Duration_infertility)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="age")%>%
  mutate(Fertile=str_replace_na(Fertile,"0"),
  Infertile=str_replace_na(Infertile,"0"))%>%
  mutate(p_value=c("<0.001","","","",""))
Duration_of_Infertility$Fertile<-as.integer(Duration_of_Infertility$Fertile)
Duration_of_Infertility$Infertile<-as.integer(Duration_of_Infertility$Infertile)
  Fertile<-as.integer(Duration_of_Infertility$Fertile)
bind_rows(Age=age,
      Gender=Gender,
      Religion=Religion,Occupation=Occupation,Level_Education=Level_Education,
      Duration_of_Infertility=Duration_of_Infertility,.id = "Variable")

# Table 2 Knowledge and common misconceptions about factors that 
# may affect sterility

# Common missconception about infertility
Common_MisConcept_About_Infertility<-Perception_propt%>%
  separate(X13..Common.misconception.about.the.causes.of.infertility...Tick.as.many.as.apply.,c("an1","an2","an3","an4"),sep = ";")%>%
  select(an1,an2,an3,an4)%>%head(10)
Common_MisConcept_About_Infertility

# Causes of Infertility Known by Respondent

Causes_Infertility_Known<-Perception_propt%>%
  separate(X12..What.are.the.causes.of.infertility.that.you.know..Tick.as.many.as.apply.,c("an1","an2","an3","an4","an5","an6","an7","an8","an9","an10","an11"),sep = ";")%>%
  select(an1,an2,an3,an4,an5,an6,an7,an8,an9,an10,an11)%>%head(10)
Causes_Infertility_Known
# Awareness of Hormonal Laboratory Investigation in Treatment of Infertility

Awareness_of_Hormonal_Laboratory_Investigation<-Perception_propt%>%
  separate(X17..Are.you.aware.of.these.hormonal.laboratory.investigations.that.can.be.conducted.for.infertility.which.aids.in.the.treatment.in.both.men.and.women...Tick.as.many.as.apply.,c("an1","an2","an3","an4","an5","an6","an7"),sep = ";")%>%
  select(an1,an2,an3,an4,an5,an6,an7)%>%head(10)
Awareness_of_Hormonal_Laboratory_Investigation

Feeling_After_Failing_Conception<-Perception_propt%>%
  separate(X22..How.do.you.feel.when.you.are.not.able.to.conceive.after.1.year.of.unprotected.sexual.intercourse.with.your.partner..Tick.as.many.as.apply.,c("an1","an2","an3","an4","an5"),sep = ";")%>%
  select(an1,an2,an3,an4,an5)%>%head(10)
Feeling_After_Failing_Conception

```

### Table on the knowledge of the various treatment option available (18)

```{r}
#Treatment Options Known to respondence

Treatment_Options_Know<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
  yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  separate(X18..What.type.of.treatment.options.do.you.know..Tick.as.many.as.apply.,c("an1","an2","an3","an4","an5","an6","an7"),sep = ";")%>%
  select(an1,an2,an3,an4,an5,an6,an7,yes_no)
# Treatment option of first respondence


treat1<-Treatment_Options_Know%>%group_by(yes_no)%>%
  count(an1)%>%pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="an1")%>%
  mutate(Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("0.16","","","","",""))
 treat1$Fertile<-as.integer(treat1$Fertile)
 treat1$Infertile<-as.integer(treat1$Infertile)
 
 treat2<-Treatment_Options_Know%>%
   group_by(yes_no)%>%
   count(an2)%>%
   pivot_wider(names_from = yes_no,values_from = n)%>%
   mutate(an2=str_replace_na(an2,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
          Infertile=str_replace_na(Infertile,"0"),p_value=c("0.23","","","","","","",""))%>%
   column_to_rownames(var="an2")
 treat2$Fertile<-as.integer(treat2$Fertile)
 treat2$Infertile<-as.integer(treat2$Infertile)

 treat3<-Treatment_Options_Know%>%
   group_by(yes_no)%>%
   count(an3)%>%
   pivot_wider(names_from = yes_no,values_from = n)%>%
   mutate(an3=str_replace_na(an3,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
          Infertile=str_replace_na(Infertile,"0"),p_value=c("0.03","","","","","","",""))%>%
   column_to_rownames(var="an3")
 treat3$Fertile<-as.integer(treat3$Fertile)
 treat3$Infertile<-as.integer(treat3$Infertile)
 
 treat4<-Treatment_Options_Know%>%
   group_by(yes_no)%>%
   count(an4)%>%
   pivot_wider(names_from = yes_no,values_from = n)%>%
   mutate(an4=str_replace_na(an4,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
          Infertile=str_replace_na(Infertile,"0"),p_value=c("0.14","","","","","",""))%>%
   column_to_rownames(var="an4")
 treat4$Fertile<-as.integer(treat4$Fertile)
 treat4$Infertile<-as.integer(treat4$Infertile)
 
 treat5<-Treatment_Options_Know%>%
   group_by(yes_no)%>%
   count(an5)%>%
   pivot_wider(names_from = yes_no,values_from = n)%>%
   mutate(an5=str_replace_na(an5,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
          Infertile=str_replace_na(Infertile,"0"),p_value=c("0.14","","","","","",""))%>%
   column_to_rownames(var="an5")
 treat5$Fertile<-as.integer(treat5$Fertile)
 treat5$Infertile<-as.integer(treat5$Infertile)
 
 treat6<-Treatment_Options_Know%>%
   group_by(yes_no)%>%
   count(an6)%>%
   pivot_wider(names_from = yes_no,values_from = n)%>%
   mutate(an6=str_replace_na(an6,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
          Infertile=str_replace_na(Infertile,"0"),p_value=c("0.52","","","","","",""))%>%
   column_to_rownames(var="an6")
 treat6$Fertile<-as.integer(treat6$Fertile)
 treat6$Infertile<-as.integer(treat6$Infertile)
 
 treat7<-Treatment_Options_Know%>%
   group_by(yes_no)%>%
   count(an7)%>%
   pivot_wider(names_from = yes_no,values_from = n)%>%
   mutate(an7=str_replace_na(an7,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
          Infertile=str_replace_na(Infertile,"0"),p_value=c("0.04","","","",""))%>%
   column_to_rownames(var="an7")
 treat7$Fertile<-as.integer(treat7$Fertile)
 treat7$Infertile<-as.integer(treat7$Infertile)
 bind_rows(ans_1=treat1,ans_2=treat2,ans_3=treat3,
           ans_4=treat4,ans_5=treat5,ans_6=treat6,ans_7=treat7,.id = "Variables") 

```


```{r}
# Table 2 Knowledge and common misconceptions about factors that may affect sterility

# Common misconception about infertility
Common_MisConcept_About_Infertility<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"), yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  separate(X13..Common.misconception.about.the.causes.of.infertility...Tick.as.many.as.apply.,c("an1","an2","an3","an4"),sep = ";")%>%
  select(an1,an2,an3,an4,yes_no)

trt1<-Common_MisConcept_About_Infertility%>%group_by(yes_no)%>%
  count(an1)%>%pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="an1")%>%
  mutate(Fertile=str_replace_na(Fertile,"0"),Infertile=str_replace_na(Infertile,"0"),p_value=c("0.10","","","","",""))
trt1$Fertile<-as.integer(trt1$Fertile)
trt1$Infertile<-as.integer(trt1$Infertile)

trt2<-Common_MisConcept_About_Infertility%>%
  group_by(yes_no)%>%
  count(an2)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an2=str_replace_na(an2,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),Infertile=str_replace_na(Infertile,"0"),p_value=c("0.06","","","","",""))%>%column_to_rownames(var="an2")
trt2$Fertile<-as.integer(trt2$Fertile)
trt2$Infertile<-as.integer(trt2$Infertile)

trt3<-Common_MisConcept_About_Infertility%>%
  group_by(yes_no)%>%
  count(an3)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an3=str_replace_na(an3,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),Infertile=str_replace_na(Infertile,"0"),p_value=c("0.45","","","","",""))%>%column_to_rownames(var="an3")
trt3$Fertile<-as.integer(trt3$Fertile)
trt3$Infertile<-as.integer(trt3$Infertile)

trt4<-Common_MisConcept_About_Infertility%>%
  group_by(yes_no)%>%
  count(an4)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an4=str_replace_na(an4,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),Infertile=str_replace_na(Infertile,"0"),p_value=c("0.31","","",""))%>%column_to_rownames(var="an4")
trt4$Fertile<-as.integer(trt4$Fertile)
trt4$Infertile<-as.integer(trt4$Infertile)

Misconception_Infertility<-bind_rows(ans_1=trt1,ans_2=trt2,ans_3=trt3,
ans_4=trt4,.id = "Variables")

Misconception_Infertility
circles1<-Misconception_Infertility%>%rownames_to_column("Treatment_Option")%>%select(-Variables,-p_value )%>%mutate(Treatment_Option=str_replace_all(Treatment_Option,"[...]\\d*",""),Treatment_Option=recode(Treatment_Option,"Obesity in both men and wome"="Obesity in both men and women"))%>%group_by(Treatment_Option)%>%
  summarise(Fertile=sum(Fertile),Infertile=sum(Infertile))

library(plotly)
library(ggpubr)
fig <- plot_ly(circles1, labels = ~Treatment_Option, values = ~Infertile, type = 'pie')
fig1 <- fig %>% layout(title = 'Treatment Options Known to Infertile Respondent', xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig1

figa <- plot_ly(circles1, labels = ~Treatment_Option, values = ~Fertile, type = 'pie')
fig <- figa %>% layout(title = 'Treatment Options Known to Fertile Respondent',xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
fig
```


```{r}

### **Causes of Infertility Known by Respondent**

Causes_Infertility_Known<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
 yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  separate(X12..What.are.the.causes.of.infertility.that.you.know..Tick.as.many.as.apply.,c("an1","an2","an3","an4","an5","an6","an7","an8","an9","an10","an11"),sep = ";")%>%
  select(an1,an2,an3,an4,an5,an6,an7,an8,an9,an10,an11,yes_no)

treta1<-Causes_Infertility_Known%>%group_by(yes_no)%>%
  count(an1)%>%pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="an1")%>%
  mutate(Fertile=str_replace_na(Fertile,"0"),
  Infertile=str_replace_na(Infertile,"0"),p_value=c("<0.001","","","","","","","","","",""))
treta1$Fertile<-as.integer(treta1$Fertile)
treta1$Infertile<-as.integer(treta1$Infertile)

treta2<-Causes_Infertility_Known%>%
  group_by(yes_no)%>%
  count(an2)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an2=str_replace_na(an2,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),
         p_value=c("0.62","","","","","","","","",""))%>%column_to_rownames(var="an2")
treta2$Fertile<-as.integer(treta2$Fertile)
treta2$Infertile<-as.integer(treta2$Infertile)

treta3<-Causes_Infertility_Known%>%
  group_by(yes_no)%>%
  count(an3)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an3=str_replace_na(an3,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("<0.21","","","","","","","","","",""))%>%
  column_to_rownames(var="an3")
treta3$Fertile<-as.integer(treta3$Fertile)
treta3$Infertile<-as.integer(treta3$Infertile)

# Error in fisher.test(.) : 
#  FEXACT error 7(location). LDSTP=18600 is too small for this problem,
# (pastp=39.6896, ipn_0:=ipoin[itp=336]=4340, stp[ipn_0]=39.0949).
# Increase workspace or consider using 'simulate.p.value=TRUE'

treta4<-Causes_Infertility_Known%>%
  group_by(yes_no)%>%
  count(an4)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an4=str_replace_na(an4,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("0.09","","","","","","","","",""))%>%
  column_to_rownames(var="an4")
treta4$Fertile<-as.integer(treta4$Fertile)
treta4$Infertile<-as.integer(treta4$Infertile)

treta5<-Causes_Infertility_Known%>%
  group_by(yes_no)%>%
  count(an5)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an5=str_replace_na(an5,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("0.09","","","","","","","",""))%>%
  column_to_rownames(var="an5")
treta5$Fertile<-as.integer(treta5$Fertile)
treta5$Infertile<-as.integer(treta5$Infertile)

treta6<-Causes_Infertility_Known%>%
  group_by(yes_no)%>%
  count(an6)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an6=str_replace_na(an6,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("0.26","","","","","","","",""))%>%
  column_to_rownames(var="an6")
treta6$Fertile<-as.integer(treta6$Fertile)
treta6$Infertile<-as.integer(treta6$Infertile)

treta7<-Causes_Infertility_Known%>%
  group_by(yes_no)%>%
  count(an7)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an7=str_replace_na(an7,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("0.39","","","","","",""))%>%
  column_to_rownames(var="an7")
treta7$Fertile<-as.integer(treta7$Fertile)
treta7$Infertile<-as.integer(treta7$Infertile)

treta8<-Causes_Infertility_Known%>%
  group_by(yes_no)%>%
  count(an8)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an8=str_replace_na(an8,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("0.15","","","","","",""))%>%
  column_to_rownames(var="an8")
treta8$Fertile<-as.integer(treta8$Fertile)
treta8$Infertile<-as.integer(treta8$Infertile)

treta9<-Causes_Infertility_Known%>%
  group_by(yes_no)%>%
  count(an9)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an9=str_replace_na(an9,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("0.19","","","",""))%>%
  column_to_rownames(var="an9")
treta9$Fertile<-as.integer(treta9$Fertile)
treta9$Infertile<-as.integer(treta9$Infertile)

treta10<-Causes_Infertility_Known%>%
  group_by(yes_no)%>%
  count(an10)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an10=str_replace_na(an10,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("0.02","",""))%>%
  column_to_rownames(var="an10")
treta10$Fertile<-as.integer(treta10$Fertile)
treta10$Infertile<-as.integer(treta10$Infertile)

treta11<-Causes_Infertility_Known%>%
  group_by(yes_no)%>%
  count(an11)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an11=str_replace_na(an11,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("0.53",""))%>%
  column_to_rownames(var="an11")
treta11$Fertile<-as.integer(treta11$Fertile)
treta11$Infertile<-as.integer(treta11$Infertile)



Known_cause<-bind_rows(ans_1=treta1,ans_2=treta2,ans_3=treta3,
                            ans_4=treta4,ans_5=treta5,ans_6=treta6,ans_7=treta7,
                            ans_8=treta8,ans_9=treta9,ans_10=treta10,
                            ans_11=treta11,.id = "Variables") 

Known_cause

circles<-Known_cause%>%rownames_to_column("Treatment_Option")%>%
  select(-Variables,-p_value )%>%mutate(Treatment_Option=str_replace_all(Treatment_Option,"[...]\\d*",""),Treatment_Option=recode(Treatment_Option,"Obesity in both men and wome"="Obesity in both men and women"))%>%group_by(Treatment_Option)%>%
  summarise(Fertile=sum(Fertile),Infertile=sum(Infertile))

library(plotly)
library(ggpubr)
fig2a <- plot_ly(circles, labels = ~Treatment_Option, values = ~Infertile, type = 'pie')
fig2 <- fig2a %>% layout(title = 'Treatment Options Known to Infertile Respondent',
     xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
     yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig2

fig3a <- plot_ly(circles, labels = ~Treatment_Option, values = ~Fertile, type = 'pie')
fig3 <- fig3a %>% layout(title = 'Treatment Options Known to Fertile Respondent',
   xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
   yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
fig3


ggplot(circles,aes(x="",y=Infertile,fill=Treatment_Option))+
  geom_bar(width = 1,stat = "identity")+coord_polar("y",start = 0)+
  theme_void()+scale_fill_grey()+
  theme(axis.title.x = element_blank())
```



```{r}
# Awareness of Hormonal Laboratory Investigation in Treatment of Infertility

Awareness_of_Hormonal_Laboratory_Investigation<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
  yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  separate(X17..Are.you.aware.of.these.hormonal.laboratory.investigations.that.can.be.conducted.for.infertility.which.aids.in.the.treatment.in.both.men.and.women...Tick.as.many.as.apply.,c("an1","an2","an3","an4","an5","an6","an7"),sep = ";")%>%
  select(an1,an2,an3,an4,an5,an6,an7,yes_no)

tret1<-Awareness_of_Hormonal_Laboratory_Investigation%>%group_by(yes_no)%>%
  count(an1)%>%pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="an1")%>%
  mutate(Fertile=str_replace_na(Fertile,"0"),Infertile=str_replace_na(Infertile,"0"),p_value=c("0.16","","","","",""))
tret1$Fertile<-as.integer(tret1$Fertile)
tret1$Infertile<-as.integer(tret1$Infertile)

tret2<-Awareness_of_Hormonal_Laboratory_Investigation%>%
  group_by(yes_no)%>%
  count(an2)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an2=str_replace_na(an2,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
  Infertile=str_replace_na(Infertile,"0"),p_value=c("0.01","","","","",""))%>%column_to_rownames(var="an2")
tret2$Fertile<-as.integer(tret2$Fertile)
tret2$Infertile<-as.integer(tret2$Infertile)

tret3<-Awareness_of_Hormonal_Laboratory_Investigation%>%
  group_by(yes_no)%>%
  count(an3)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an3=str_replace_na(an3,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
  Infertile=str_replace_na(Infertile,"0"),p_value=c("<0.001","","","","",""))%>%column_to_rownames(var="an3")
tret3$Fertile<-as.integer(tret3$Fertile)
tret3$Infertile<-as.integer(tret3$Infertile)

tret4<-Awareness_of_Hormonal_Laboratory_Investigation%>%
  group_by(yes_no)%>%
  count(an4)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an4=str_replace_na(an4,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),Infertile=str_replace_na(Infertile,"0"),p_value=c("0.18","","","",""))%>%
  column_to_rownames(var="an4")
tret4$Fertile<-as.integer(tret4$Fertile)
tret4$Infertile<-as.integer(tret4$Infertile)

tret5<-Awareness_of_Hormonal_Laboratory_Investigation%>%
  group_by(yes_no)%>%
  count(an5)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an5=str_replace_na(an5,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("0.02","","",""))%>%column_to_rownames(var="an5")
tret5$Fertile<-as.integer(tret5$Fertile)
tret5$Infertile<-as.integer(tret5$Infertile)

tret6<-Awareness_of_Hormonal_Laboratory_Investigation%>%
  group_by(yes_no)%>%
  count(an6)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an6=str_replace_na(an6,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("0.18","",""))%>%
  column_to_rownames(var="an6")
tret6$Fertile<-as.integer(tret6$Fertile)
tret6$Infertile<-as.integer(tret6$Infertile)

tret7<-Awareness_of_Hormonal_Laboratory_Investigation%>%
  group_by(yes_no)%>%
  count(an7)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an7=str_replace_na(an7,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
  Infertile=str_replace_na(Infertile,"0"),p_value=c("0.94",""))%>%
  column_to_rownames(var="an7")
tret7$Fertile<-as.integer(tret7$Fertile)
tret7$Infertile<-as.integer(tret7$Infertile)
Treatment_Option<-bind_rows(ans_1=tret1,ans_2=tret2,ans_3=tret3,
                            ans_4=tret4,ans_5=tret5,ans_6=tret6,ans_7=tret7,.id = "Variables") 

circles2<-Treatment_Option%>%rownames_to_column("Treatment_Option")%>%
  select(-Variables,-p_value )%>%mutate(Treatment_Option=str_replace_all(Treatment_Option,"[...]\\d*",""),Treatment_Option=recode(Treatment_Option,"Obesity in both men and wome"="Obesity in both men and women"))%>%group_by(Treatment_Option)%>%
  summarise(Fertile=sum(Fertile),Infertile=sum(Infertile))

fig4a <- plot_ly(circles2, labels = ~Treatment_Option, values = ~Infertile, type = 'pie')
fig4 <- fig4a %>% layout(title = 'Treatment Options Known to Infertile Respondent',xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig4

fig5a <- plot_ly(circles2, labels = ~Treatment_Option, values = ~Fertile, type = 'pie')
fig5 <- fig5a %>% layout(title = 'Treatment Options Known to Fertile Respondent',xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
fig5

```



```{r}
# Feeling After Failing Conception

Feeling_After_Failing_Conception<-Perception_propt%>%
  mutate(Duration_infertility=recode(X6..Duration.of.infertility,"Nil:"="Nil"),
  yes_no=ifelse(Duration_infertility=="Nil","Fertile","Infertile"))%>%
  separate(X22..How.do.you.feel.when.you.are.not.able.to.conceive.after.1.year.of.unprotected.sexual.intercourse.with.your.partner..Tick.as.many.as.apply.,c("an1","an2","an3","an4","an5"),sep = ";")%>%
  select(an1,an2,an3,an4,an5,yes_no)

trat1<-Feeling_After_Failing_Conception%>%group_by(yes_no)%>%
  count(an1)%>%pivot_wider(names_from = yes_no,values_from = n)%>%
  column_to_rownames(var="an1")%>%
  mutate(Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("<0.001","","",""))
trat1$Fertile<-as.integer(trat1$Fertile)
trat1$Infertile<-as.integer(trat1$Infertile)

trat2<-Feeling_After_Failing_Conception%>%
  group_by(yes_no)%>%
  count(an2)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an2=str_replace_na(an2,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("0.002","","",""))%>%column_to_rownames(var="an2")
trat2$Fertile<-as.integer(trat2$Fertile)
trat2$Infertile<-as.integer(trat2$Infertile)

trat3<-Feeling_After_Failing_Conception%>%
  group_by(yes_no)%>%
  count(an3)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an3=str_replace_na(an3,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("0.45","","",""))%>%
  column_to_rownames(var="an3")
trat3$Fertile<-as.integer(trat3$Fertile)
trat3$Infertile<-as.integer(trat3$Infertile)

trat4<-Feeling_After_Failing_Conception%>%
  group_by(yes_no)%>%
  count(an4)%>%
  pivot_wider(names_from = yes_no,values_from = n)%>%
  mutate(an4=str_replace_na(an4,"Not Selected"),Fertile=str_replace_na(Fertile,"0"),
         Infertile=str_replace_na(Infertile,"0"),p_value=c("0.25",""))%>%
  column_to_rownames(var="an4")
trat4$Fertile<-as.integer(trat4$Fertile)
trat4$Infertile<-as.integer(trat4$Infertile)

Feeling_Failing<-bind_rows(ans_1=trat1,ans_2=trat2,ans_3=trat3,
                            ans_4=trat4,.id = "Variables") 

circles3<-Feeling_Failing%>%rownames_to_column("Treatment_Option")%>%
  select(-Variables,-p_value )%>%mutate(Treatment_Option=str_replace_all(Treatment_Option,"[...]\\d*",""),Treatment_Option=recode(Treatment_Option,"Obesity in both men and wome"="Obesity in both men and women"))%>%group_by(Treatment_Option)%>%
  summarise(Fertile=sum(Fertile),Infertile=sum(Infertile))

fig6a <- plot_ly(circles3, labels = ~Treatment_Option, values = ~Infertile, type = 'pie')
fig6 <- fig6a %>% layout(title = 'Treatment Options Known to Infertile Respondent',
    xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
     yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))

fig6

fig7a <- plot_ly(circles2, labels = ~Treatment_Option, values = ~Fertile, type = 'pie')
fig7 <- fig7a %>% layout(title = 'Treatment Options Known to Fertile Respondent',
        xaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE),
       yaxis = list(showgrid = FALSE, zeroline = FALSE, showticklabels = FALSE))
fig7

```

